### ISSUE TITLE
Excessive compilation times

### ISSUE THREAD

**Issue by andreasvarga** [andreasvarga/DescriptorSystems.jl#6]
After the transition to `v2.0` of [Polynomials](https://github.com/JuliaMath/Polynomials.jl), excessive compilation times resulted, for example, 50 minutes vs. the usual 16-20 minutes for a runtest. A similar behaviour occurred for [MatrixPencils](https://github.com/andreasvarga/MatrixPencils.jl), where a change from type `Polynomial` to `Polynomial{T}` in just one function (`poly2pm`) solved the problem!

**Comment by jverzani** [comment]
I'm not sure where the issue is, but I found this big variance between the `PolynomialRatios` function I started and your handling of transfer functions (admittedly, my version doesn't carry all the field information yours does, but I don't think that is the issue):

```
ulia> @time z = variable(RationalFunction)
  0.000002 seconds (5 allocations: 416 bytes)
(1.0*x) // (1.0)

julia> @time Gd = [z^2 z/(z-2); 0 1/z];
  1.232500 seconds (3.63 M allocations: 189.930 MiB, 8.93% gc time)

julia> @time z = rtf('z');

  0.140046 seconds (203.57 k allocations: 10.538 MiB, 11.60% gc time)

julia> @time Gd = [z^2 z/(z-2); 0 1/z];
 18.971481 seconds (50.86 M allocations: 2.854 GiB, 6.63% gc time)
```

It isn't that your methods are slow either, as the difference seems all to be compile time:

```
julia> @time z = variable(RationalFunction)
  0.000003 seconds (5 allocations: 416 bytes)
(1.0*x) // (1.0)

julia> @time Gd = [z^2 z/(z-2); 0 1/z];
  0.000146 seconds (199 allocations: 9.875 KiB)

julia> @time z = rtf('z');
  0.000019 seconds (16 allocations: 1.125 KiB)

julia> @time Gd = [z^2 z/(z-2); 0 1/z];
  0.000117 seconds (134 allocations: 8.453 KiB)
```

**Comment by andreasvarga** [comment]
This is very disturbing. On my machine
```
julia> @time Gd = [z^2 z/(z-2); 0 1/z]
 13.008802 seconds (51.68 M allocations: 2.894 GiB, 8.70% gc time)
```
Interestingly, 
```
julia> @time Gd = [z^2 z/(z-2); zero(z) 1/z]
  0.787328 seconds (4.43 M allocations: 218.295 MiB, 4.43% gc time)
```
which is the same thing, excepting the "0" .

I prepared a new version with some fixes. 
For the statement 
` @time sysd = dss(Gd,minimal = true,Ts = 1); `
I succeded to reduce the compilation time from 600 seconds to 20 seconds!!! This reduction is the result of enforcing the type `Array{RationalTransferFunction{Int64,:z},2}` for `Gd`, while previously this was `Array{RationalTransferFunction{Int64,X} where X,2}`, which probably led to the huge compilation effort.

**Comment by jverzani** [comment]
This is good news. Concrete types make a big difference. (As an aside, in your `RationalTransferFunction` struct, you should use the concrete `Float64` instead of `Real`.) 

I'm guessing, but we have a tension between flexibility and performance. The use of 0 as opposed to `zero(z)` means we end up compiling different versions for integer input (and if there was a 0.0, floating point input). Whereas using `zero(z)` doesn't, as that function is already compiled for such inputs. That seems like a cost we shouldn't mind paying for convenience and composability.

The other issue is the inherent type stability introduced when we allow constant polynomials to be treated like scalars. Look at the difference bewteen these two sums:

```
julia> p,q = Polynomial([1,2],:x), Polynomial([1,2],:y)
julia> @code_warntype p+p
julia> @code_warntype p+one(q)
```
The first has no type instability (we have a specific method to handle the case when the symbols agree), the second has one (as the type doesn't know `one(q)` will be a constant so can be added). So this comes at a performance cost. I don't know for sure but suspect this one is costly. (For example, the type of `one(p) + one(q)` will differ from that of `one(q) + one(p)`, so we aren't giving any help to the compiler) My guess is the ambiguity in the symbol (the `where {X}` part) comes from this convenience, though am not sure. By enforcing this you really are helping out.
